### ISSUE TITLE
Unable to add other chains 

### ISSUE THREAD

**Issue by 0xFable** [oraichain/vscode-cosmwasm#24]
Was giving this a go and trying to play around with some other chains but was unable to add a new chain other than the defaults. 

I got a chain.json from the chain-registry repo 
Selected this file using file picker in CW IDE 
It shows the file selected

IDE still shows Oraichain for queryies and such 
I click add new chain 
I get error adding chain 

No juno chain added

**Comment by im6h** [comment]
Can you show me the json file you added?  You can check a template in this [repo](https://github.com/oraichain/cw-ide-webview)

**Comment by kleimanb81** [comment]
Did you create a PR for the chain?

**Comment by kleimanb81** [comment]
At the moment, you need to create a PR submitting your network information. Afterward, we will review and merge it. Below is an example of the network's metadata:

{
    "rpc": "https://testnet-rpc.orai.io",
    "rest": "https://testnet-lcd.orai.io",
    "chainId": "Oraichain-testnet",
    "chainName": "Oraichain Foobar",
    "stakeCurrency": {
        "coinDenom": "ORAI",
        "coinMinimalDenom": "orai",
        "coinDecimals": 6,
        "coinGeckoId": "oraichain-token",
        "coinImageUrl": "http://localhost:3000/public/assets/tokens/orai.png"
    },
    "bip44": {
        "coinType": 118
    },
    "bech32Config": {
        "bech32PrefixAccAddr": "orai",
        "bech32PrefixAccPub": "oraipub",
        "bech32PrefixConsAddr": "oraivalcons",
        "bech32PrefixConsPub": "oraivalconspub",
        "bech32PrefixValAddr": "oraivaloper",
        "bech32PrefixValPub": "oraivaloperpub"
    },
    "currencies": [
        {
            "coinDenom": "ORAI",
            "coinMinimalDenom": "orai",
            "coinDecimals": 6,
            "coinGeckoId": "oraichain-token",
            "coinImageUrl": "http://localhost:3000/public/assets/tokens/orai.png"
        }
    ],
    "feeCurrencies": [
        {
            "coinDenom": "ORAI",
            "coinMinimalDenom": "orai",
            "coinDecimals": 6,
            "coinGeckoId": "oraichain-token",
            "coinImageUrl": "http://localhost:3000/public/assets/tokens/orai.png"
        }
    ],
    "gasPriceStep": {
        "low": 0,
        "average": 0.0025,
        "high": 0.004
    },
    "features": [
        "stargate",
        "ibc-transfer",
        "cosmwasm"
    ],
    "cosmwasmVersion": "0.13.2" // the cosmwasm std your network is using.
}
It follows the same format as that of Keplr so that the webview can work with the extension. We also add a few attributes, which include comments above.

Please append the network information into the config file if you prefer to let your network be included in the IDE permanently. Please note that this requires reviewing & a pull request. The IDE also provides a feature that helps you add and remove custom networks & store them locally.

**Comment by ducphamle2** [comment]
@kleimanb81 submitting a PR is for adding the chain config permanently. Normally, the devs can add new chains using the "Add new chain" button

**Comment by Climbinb** [comment]
Oh really? Ty for letting me know. That's much less work than a pr for each.
